# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x2e3440ff
rootcolor = 0x2e3440ff
bordercolor = 0x707d99ff
focuscolor = 0x8fbcbbff
maximizescreencolor = 0x88c0d0ff
urgentcolor = 0xbf616aff
scratchpadcolor = 0x5e81acff
globalcolor = 0x2e6b69ff
overlaycolor = 0x226e83ff
